name: Front Lights Firmware
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: xanderhendriks/action-build-stm32cubeide@v7.2
        with:
          project-path: 'front-lights-firmware'
          project-target: 'FrontLightsFirmware'

      - uses: actions/upload-artifact@v3
        with:
          name: 'Front Lights Release Binary'
          path: ./front-lights-firmware/Debug/*.elf
          if-no-files-found: error
