name: Rear Lights Firmware
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: Solar-Gators/STM32-Infrastructure@main
        with:
          project-path: 'rear-lights-firmware'
          project-target: 'RearLightsFirmware'

      - uses: actions/upload-artifact@v3
        with:
          name: 'Rear Lights Release Binary'
          path: ./rear-lights-firmware/Debug/*.elf
          if-no-files-found: error
