name: Steering Firmware
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: Solar-Gators/STM32-Infrastructure@main
        with:
          project-path: 'steering-firmware'
          project-target: 'SteeringWheel2023'

      - uses: actions/upload-artifact@v3
        with:
          name: 'Steering Release Binary'
          path: ./steering-firmware/Debug/*.elf
          if-no-files-found: error
